a/urls.py
from django.urls import path, include
from a.views import indexA, indexaaa, indexbbb, indexccc

app_name = 'a' # 앱 이름 지정

urlpatterns = [
    path('', indexA, name='sampleA'), # name 지정해서 html 파일에서 템플릿 태그로 사용할 거야!
    path('aaa/', indexaaa, name='sampleaaa'), # aaa 다음 어떤 문자열이 나오던 간에 a.urls.py로 이동해라
    path('bbb/', indexbbb),
    path('ccc/', indexccc),
]

djangomtv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main.views import index, test, sample # main의 views.py에서 index 모듈 가져다 사용할 거야!
from a.views import indexA
from b.views import indexB, indexBdetail
#from c.views import indexC
from c.views import BlogList, BlogDetail
from d.views import indexD, testview, SignupView, LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('sample', sample),
    path('testtest/', test), # main의 views.py 파일에 test 함수 작성하자
    path('aa/', include('a.urls')),
    path('bb/', indexB),
    path('bb/<int:pk>/', indexBdetail), # 숫자로 오는 값을 받아서 인자로 넘겨줌
    #path('cc/', indexC),
    path('cc/', BlogList.as_view()),
    path('cc/<int:pk>/', BlogDetail.as_view()),
    path('dd/', indexD),
    path('dd/test', testview),
    path('dd/signup/', SignupView.as_view()),
    path('dd/login/', LoginView.as_view()),
    path('dd/logout/', LogoutView.as_view()),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a/models.py
from django.db import models

# Create your models here.

b/models.py
from django.db import models
import random
from django.contrib.auth.models import User

class Blog(models.Model): # 클래스 작성시 변수만 지정하면 됨
    title = models.CharField(max_length=100) # 게시물제목: 문자열 field, 최대 길이 100 제한
    # author : 인증 뒤에서 언급함
    # 저자는 한 명뿐이어야 하기 때문에 외래키 관계로 지정
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    contents= models.TextField() # 내용
    #img = models.ImageField(blank=True)
    r = random.randint(1, 10000)
    img = models.ImageField(upload_to='bb/%Y/%m/%d/{r}', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True) # 처음 생성한 날짜를 저장하고 다시 갱신하지 않음
    modified_at = models.DateTimeField(auto_now=True, null=True) # 수정될 때마다 시간 저장
    
    def __str__(self):
        return f'제목 : {self.title}, 좋아요 수 : {self.contents}' 
    
#lass 댓글():    # 게시물 : 댓글  =>  1:N 혹은 N:N

c/models.py
from django.db import models

# Create your models here.

d/models.py
from django.db import models

# Create your models here.

e/models.py
from django.db import models

# 학생
class Student(models.Model):
    number = models.IntegerField("학번")
    name = models.CharField("이름", max_length=20)
    major = models.ForeignKey(verbose_name="주전공", to='e.Department', on_delete=models.SET_NULL, null=True)
    friends = models.ManyToManyField(verbose_name="친구들", to='self', db_table='e_friendship', blank=True)

    def __str__(self):
        return self.name


# 학과
class Department(models.Model):
    name = models.CharField("학과명", max_length=20)
    head = models.CharField("학과장", max_length=20)

    def __str__(self):
        return self.name

main/models.py
from django.db import models

# Create your models here.
class Notice(models.Model): # 클래스 작성시 변수만 지정하면 됨
    title = models.CharField(max_length=100) # 게시물제목: 문자열 field, 최대 길이 100 제한
    likeCount = models.IntegerField() # 좋아요수
    viewCount= models.IntegerField() # 뷰수
    contents= models.TextField() # 내용
    
    def __str__(self):
        return f'제목 : {self.title}, 좋아요 수 : {self.likeCount}, 조회수 : {self.viewCount}' # title이 Notice를 대표하는 문자열 값이야
    
#lass 댓글():    # 게시물 : 댓글  =>  1:N 혹은 N:N

a/views.py
from django.shortcuts import render

def indexA(request):
    return render(request, 'indexA.html')
def indexaaa(request):
    return render(request, 'indexaaa.html')
def indexbbb(request):
    return render(request, 'indexbbb.html')
def indexccc(request):
    return render(request, 'indexccc.html')

b/views.py
from django.shortcuts import render
from .models import Blog

def indexB(request):
    context = Blog.objects.all()
    return render(request, 'indexB.html', {'context':context})

def indexBdetail(request, pk):
    blog = Blog.objects.get(pk=pk)
    context = {
        'blog':blog,
    }
    return render(request, 'indexBdetail.html', context)

c/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from b.models import Blog

# def indexC(request):
#     return render(request, 'indexC.html')

class BlogList(ListView):
    model = Blog
    template_name = 'indexC.html' #class명_list.html 파일을 자동으로 찾음

class BlogDetail(DetailView):
    model = Blog
    template_name = 'indexCdetail.html' #class명_detail.html 파일을 자동으로 찾음

d/views.py
from django.shortcuts import render # 기본적인 인증 모델
from django.contrib.auth import get_user_model # 기본적인 유저 모델
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView as _LoginView, LogoutView as _LogoutView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required

def indexD(request):
    return render(request, 'indexD.html')


class SignupView(CreateView):
    template_name = 'signup.html'
    form_class = UserCreationForm
    model = get_user_model()

    def get_success_url(self):
        return '/dd/login/'


class LoginView(_LoginView):
    template_name = 'login.html'


class LogoutView(_LogoutView):
    template_name = 'logout.html'

    
class Profile(DetailView):
    pass


@login_required
def testview(request):
    return render(request, 'indexD.html')

e/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Notice

def index(request):
    print(request) # 터미널에 사용자의 요청 사항 출력하기
    print(type(request))
    print(dir(request))
    print('============')
    l = [100, 200, 300]
    print(l)
    print(request.POST) # 터미널에 POST 방식으로 넘어온 사용자의 요청 사항 출력하기
    return render(request, 'index.html', {'valueList':l})

def test(request):
    return render(request, 'test.html')

# def test(request):
#     return redirect('/') # 요청 받고 root 파일로 가라

# def test(request):
#     return HttpResponse('Hello world') # url에 /testtest 추가하면 Hello world 출력됨

def test(request):
    d = {'name':'je', 'age':24}
    return JsonResponse(d)

# def sample(request):
#     d = {'name':'je', 'age':24}
#     l = [100, 200, 300]
#     return render(request, 'sample.html', {'value':d}) # templates에서 value라는 이름으로 l을 사용할 것임!

def sample(request):
    d = Notice.objects.all()
    print(d)
    return render(request, 'sample.html', {'value':d})

a/templates/indexA.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world A</h1>
    <p>
        내 위치는 지금 djangomtv/a/templates/indexA.html 이야!
    </p>
    <a href="{% url 'a:sampleaaa' %}">aaa로 이동!!</a>
</body>
</html>

a/templates/indexaaa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world aaa</h1>
    <p>
        내 위치는 djangomtv/a/templates/indexaaa.html 이야
    </p>
    <a href="{% url 'a:sampleA' %}">aa로 이동!!</a>
</body>
</html>

b/templates/indexB.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <h1>
    hello world B
    </h1>
    <table class="table table-hover">
        <tr>
            <th>제목</th>
            <th>내용</th>
        </tr>
        {% for blog in context %}
        <tr>
            <td>
            <a href="/bb/{{blog.id}}/">{{ blog.title }}</a>
            </td>
            <td>
            {{ blog.contents }}
            </td>
        </tr>
        
        {% endfor %}
        
    </table>
</body>
</html>

b/templates/indexBdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>
    hello world B
    </h1>
    {{blog.title}}
    {{blog.contents}}
    {%if blog.img%}
        <img src="{{blog.img.url}}" height="200px">
    {%endif%}
</body>
</html>

c/templates/indexC.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world C</h1>
    {% for i in blog_list %}
        <h1>{{ i.title }}</h1>
        <p>{{ i.contents }}</p>
    {% endfor %}
</body>
</html>

c/templates/indexCdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world C</h1>
    <h1>{{ blog.title }}</h1>
    <p>{{ blog.contents }}</p>
</body>
</html>

d/templates/indexD.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world D</h1>
    {% if user.is_authenticated %}
        <p>로그인 된 유저 : {{ user }}</p>
        <a href="/dd/logout/">로그아웃</a>
    {% else %}
        <a href="/dd/signup/">회원 가입</a>
        <a href="/dd/login/">로그인</a>
    {% endif %}
</body>
</html>

d/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>로그인</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="로그인">
    </form>

    <a href="/dd/">홈으로</a>
    <a href="/dd/signup/">회원가입</a>
</body>
</html>

d/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h3>로그아웃 되었습니다.</h3>
    <a href="/dd/">홈으로</a>
    <a href="/dd/login/">로그인 하기</a>
</body>
</html>

d/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>회원 가입</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="가입하기">
    </form>
</body>
</html>

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>
    hello world main > templates > index.html
    </h1>
    
    <!--body 내용-->
    {% block body %}
    {% endblock body %}
    
    <!--footer 내용-->
    <p>
        footer
    </p>
</body>
</html>

main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<img src="{%static 'jeju.jpg'%}" alt='' width='200px'>
    <h1>{{valueList}}</h1>
    <form action='/' method="POST"> <!-- POST 방식으로 사용자가 요청하면 views.py에서 request로 받았을 때 정보 출력 가능 -->
        {% csrf_token %}

        <input type='text' name='id'><br>
        <input type='password' name='pw'><br>
        <input type='submit' name='로그인'>
        
    </form>
{% endblock body %}

main/templates/sample.html
<h1>{{value}}</h1>
<p>{{value.1.title}}</p>
    
{% for i in value %}
    <h1>{{forloop.counter}} - {{i.title}}</h1>
    <!-- counter0 : 인덱스 0부터 시작 -->
    <!-- revcounter0 : 인덱스 역순, 마지막 인덱스가 0이 되게 -->
    <p>{{i.contents}}</p>
    <p>{{i.viewCount}}</p>
    
    {% if i.viewCount > 7 %}
        <p>뷰 수가 많습니다.</p>
    {% elif i.viewCount > 5 %}
        <p>콘텐츠가 반응을 보이고 있습니다.</p>
    {% else %}
        <p>콘텐츠 홍보를 더 해주세요..</p>
    {% endif %}
    
{% endfor %}

{% with value='hello world' %}
    <h1>{{value}}</h1>
{% endwith %}

{# 주석입니다 #}
{% comment 'hojun' %}
  <p>안보임, 소스코드 보류 용도로도 사용</p>
{% endcomment %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <p>
    원래는 이곳이 djangomtv > templates > index.html 였는데 <br>
    index.html 자체를 block body 태그를 사용해     <br>
    djangomtv/templates/base.html <br>
    이 위치로 끌어옴 <br>
    </p>
    <h1>
        여기서부터 block body 시작
    </h1>
    <!--body 내용-->
    {% block body %}
    {% endblock body %}
    <h1>
        여기까지 block body 끝
    </h1>
    <!--footer 내용-->
    <p>
        footer
    </p>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
여기서부터 djangomtv > templates > index.html <br>
<img src="{%static 'jeju.jpg'%}" alt='' width='200px'>
<br>
djangomtv/main/views.py의 index() 함수에서 보내는 리스트
<br>
<h1>{{valueList}}</h1>
<h1>{{valueList.2}}</h1>
<br>
    <form action='/' method="POST"> <!-- POST 방식으로 사용자가 요청하면 views.py에서 request로 받았을 때 정보 출력 가능 -->
        {% csrf_token %}

        <input type='text' name='id'><br>
        <input type='password' name='pw'><br>
        <input type='submit' name='로그인'>
    </form>

    <a href='https://djangomtv-lnurf.run.goorm.io/testtest'>이동</a><br>
여기까지 djangomtv > templates > index.html <br>
{% endblock body %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>
        Hello test page!
    </h1>
</body>
</html>